# docker run -p 5432:5432 -e POSTGRES_PASSWORD=docker postgres
# docker-compose up
name: pokemon-db
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pokemon
    volumes:
      - pokemon_pg_data:/postgres

volumes:
  pokemon_pg_data:
